source 'http://git.sdos.es/ios/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

#=================================================
#=====================Project=====================
#Poner aquí todas las librerías propias del proyecto



#=================================================
#=================================================

#=====================Core=====================
pod 'SDOS', :podspec => '../../../SDOS/SDOS.podspec'
pod 'SDOSLocalizableString', :podspec => '../../../SDOSLocalizableString/SDOSLocalizableString.podspec'
pod 'SDOSLoader', :path => '../../'

#=====================Script post install=====================
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = "NO"
            config.build_settings['ENABLE_BITCODE'] = "NO"
            config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = "YES"
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
