//  FICHERO AUTOGENERADO - NO MODIFICAR
//  StoryboardConstants.m
//
//  Created by SDOS
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NSString * const SBNameExampleLoader = @"ExampleLoader";

NSString * const SBNameExampleLoaderTV = @"ExampleLoaderTV";

 //
 // ExampleLoader.m
 // Generated by seguecode


//@implementation ExampleLoaderViewController (ExampleLoader)
//
//@end
//@implementation UINavigationController (ExampleLoader)
//
//@end
//@implementation DocumentationLoaderViewController (ExampleLoader)
//
//@end

// Auto generated file - any changes will be lost


#pragma mark - navigationController.storyboardIdentifier
NSString * const ExampleLoaderNavigationController = @"ExampleLoaderNavigationController";

#pragma mark - storyboardNames
NSString * const ExampleLoader = @"ExampleLoader";
NSString * const ExampleLoaderTV = @"ExampleLoaderTV";


