//  FICHERO AUTOGENERADO - NO MODIFICAR
//  StoryboardConstants.h
//
//  Created by SDOS
//

#import <Foundation/Foundation.h>

extern NSString * const SBNameExampleLoader;

extern NSString * const SBNameExampleLoaderTV;

 //
 // ExampleLoader.h
 // Generated by seguecode

#pragma once

#import <UIKit/UIKit.h>

//#import "ExampleLoaderViewController.h"
//
//@interface ExampleLoaderViewController (ExampleLoader)
//
//@end
//@interface UINavigationController (ExampleLoader)
//
//@end
//#import "DocumentationLoaderViewController.h"
//
//@interface DocumentationLoaderViewController (ExampleLoader)
//
//@end

// Auto generated file - any changes will be lost

#import <Foundation/Foundation.h>

#pragma mark - navigationController.storyboardIdentifier
extern NSString * const ExampleLoaderNavigationController;

#pragma mark - storyboardNames
extern NSString * const ExampleLoader;
extern NSString * const ExampleLoaderTV;


